# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vault.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vault.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvault.proto\x12\x05vault\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\")\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\x05\"<\n\x0cSearchResult\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x02\"6\n\x0eSearchResponse\x12$\n\x07results\x18\x01 \x03(\x0b\x32\x13.vault.SearchResult\"\x1c\n\x0cIndexRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1f\n\rIndexResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc5\x01\n\x0cVaultService\x12<\n\rHealthService\x12\x14.vault.HealthRequest\x1a\x15.vault.HealthResponse\x12<\n\rSearchService\x12\x14.vault.SearchRequest\x1a\x15.vault.SearchResponse\x12\x39\n\x0cIndexService\x12\x13.vault.IndexRequest\x1a\x14.vault.IndexResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=22
  _globals['_HEALTHREQUEST']._serialized_end=37
  _globals['_HEALTHRESPONSE']._serialized_start=39
  _globals['_HEALTHRESPONSE']._serialized_end=71
  _globals['_SEARCHREQUEST']._serialized_start=73
  _globals['_SEARCHREQUEST']._serialized_end=114
  _globals['_SEARCHRESULT']._serialized_start=116
  _globals['_SEARCHRESULT']._serialized_end=176
  _globals['_SEARCHRESPONSE']._serialized_start=178
  _globals['_SEARCHRESPONSE']._serialized_end=232
  _globals['_INDEXREQUEST']._serialized_start=234
  _globals['_INDEXREQUEST']._serialized_end=262
  _globals['_INDEXRESPONSE']._serialized_start=264
  _globals['_INDEXRESPONSE']._serialized_end=295
  _globals['_VAULTSERVICE']._serialized_start=298
  _globals['_VAULTSERVICE']._serialized_end=495
# @@protoc_insertion_point(module_scope)
